[[redirects]]
from = "https://voter-admin.netlify.app/*"
to = "https://voter.dk-gl.eu/:splat"
force = true
status = 301

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
port = 8802
publish = "dist/spa"
